"""edit questions

Revision ID: 8c9508c5cc59
Revises: 9e92c3140969
Create Date: 2023-02-21 23:06:03.816362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9508c5cc59'
down_revision = '9e92c3140969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
