"""edit question

Revision ID: 9e92c3140969
Revises: f06f52ece56b
Create Date: 2023-02-20 23:46:53.461745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e92c3140969'
down_revision = 'f06f52ece56b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
