"""edit question-answers

Revision ID: f06f52ece56b
Revises: ede3a8103978
Create Date: 2023-02-20 23:44:34.208543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06f52ece56b'
down_revision = 'ede3a8103978'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
